### ISSUE TITLE
I have a problem to install

### ISSUE THREAD

**Issue by AgenceUpMotion** [terminal42/contao-autoregistration#6] opened 2019-10-31 14:02 UTC
s] Your requirements could not be resolved to an installable set of packages.
[2397.1MiB/60.28s] 
  Problem 1
    - Conclusion: don't install terminal42/contao-autoregistration 2.0.1
    - Conclusion: don't install contao-components/contao 7.1.5
    - contao/core-bundle 4.6.0 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.1 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.10 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.11 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.12 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.13 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.14 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.2 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.3 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.4 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.5 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.6 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.7 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.8 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.6.9 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.0 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.1 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.2 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.3 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.4 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.5 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.6 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.7.7 requires contao-components/contao ^8.0 -> satisfiable by contao-components/contao[8.0.0, 8.0.1, 8.0.2, 8.0.3].
    - contao/core-bundle 4.8.0 requires contao-components/contao ^9.0 -> satisfiable by contao-components/contao[9.0.0].
    - contao/core-bundle 4.8.1 requires contao-components/contao ^9.0 -> satisfiable by contao-components/contao[9.0.0].
    - contao/core-bundle 4.8.2 requires contao-components/contao ^9.0 -> satisfiable by contao-components/contao[9.0.0].
    - contao/core-bundle 4.8.3 requires contao-components/contao ^9.0 -> satisfiable by contao-components/contao[9.0.0].
    - contao/core-bundle 4.8.4 requires contao-components/contao ^9.0 -> satisfiable by contao-components/contao[9.0.0].
    - Can only install one of: contao-components/contao[8.0.0, 7.1.5].
    - Can only install one of: contao-components/contao[8.0.1, 7.1.5].
    - Can only install one of: contao-components/contao[8.0.2, 7.1.5].
    - Can only install one of: contao-components/contao[8.0.3, 7.1.5].
    - Can only install one of: contao-components/contao[9.0.0, 7.1.5].
    - Installation request for contao-components/contao (locked at 7.1.5) -> satisfiable by contao-components/contao[7.1.5].
    - Conclusion: don't install terminal42/contao-autoregistration 2.0.1|don't install contao-components/dropzone 4.3.0|install contao/core-bundle 4.6.0|install contao/core-bundle 4.6.1|install contao/core-bundle 4.6.10|install contao/core-bundle 4.6.11|install contao/core-bundle 4.6.12|install contao/core-bundle 4.6.13|install contao/core-bundle 4.6.14|install contao/core-bundle 4.6.2|install contao/core-bundle 4.6.3|install contao/core-bundle 4.6.4|install contao/core-bundle 4.6.5|install contao/core-bundle 4.6.6|install contao/core-bundle 4.6.7|install contao/core-bundle 4.6.8|install contao/core-bundle 4.6.9|install contao/core-bundle 4.7.0|install contao/core-bundle 4.7.1|install contao/core-bundle 4.7.2|install contao/core-bundle 4.7.3|install contao/core-bundle 4.7.4|install contao/core-bundle 4.7.5|install contao/core-bundle 4.7.6|install contao/core-bundle 4.7.7|install contao/core-bundle 4.8.0|install contao/core-bundle 4.8.1|install contao/core-bundle 4.8.2|install contao/core-bundle 4.8.3|install contao/core-bundle 4.8.4
    - Installation request for terminal42/contao-autoregistration ^2.0 -> satisfiable by terminal42/contao-autoregistration[2.0.0, 2.0.1].
    - Conclusion: don't install contao-components/dropzone 4.3.0|install contao/core-bundle 4.6.0|install contao/core-bundle 4.6.1|install contao/core-bundle 4.6.10|install contao/core-bundle 4.6.11|install contao/core-bundle 4.6.12|install contao/core-bundle 4.6.13|install contao/core-bundle 4.6.14|install contao/core-bundle 4.6.2|install contao/core-bundle 4.6.3|install contao/core-bundle 4.6.4|install contao/core-bundle 4.6.5|install contao/core-bundle 4.6.6|install contao/core-bundle 4.6.7|install contao/core-bundle 4.6.8|install contao/core-bundle 4.6.9|install contao/core-bundle 4.7.0|install contao/core-bundle 4.7.1|install contao/core-bundle 4.7.2|install contao/core-bundle 4.7.3|install contao/core-bundle 4.7.4|install contao/core-bundle 4.7.5|install contao/core-bundle 4.7.6|install contao/core-bundle 4.7.7|install contao/core-bundle 4.8.0|install contao/core-bundle 4.8.1|install contao/core-bundle 4.8.2|install contao/core-bundle 4.8.3|install contao/core-bundle 4.8.4
    - terminal42/contao-autoregistration 2.0.0 requires contao/core-bundle ^4.5 -> satisfiable by contao/core-bundle[4.5.0, 4.5.1, 4.5.10, 4.5.11, 4.5.12, 4.5.13, 4.5.14, 4.5.2, 4.5.3, 4.5.4, 4.5.5, 4.5.6, 4.5.7, 4.5.8, 4.5.9, 4.6.0, 4.6.1, 4.6.10, 4.6.11, 4.6.12, 4.6.13, 4.6.14, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8, 4.6.9, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 4.8.0, 4.8.1, 4.8.2, 4.8.3, 4.8.4].
    - contao/core-bundle 4.5.0 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.1 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.10 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.11 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.12 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.13 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.14 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.2 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.3 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.4 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.5 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.6 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.7 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.8 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - contao/core-bundle 4.5.9 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.4.0, 5.5.0].
    - Can only install one of: contao-components/dropzone[5.0.1, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.1.0, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.1.1, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.2.0, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.3.0, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.3.1, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.4.0, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.5.0, 4.3.0].
    - Installation request for contao-components/dropzone (locked at 4.3.0) -> satisfiable by contao-components/dropzone[4.3.0].

[2397.1MiB/60.28s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[763.8MiB/69.48s] Memory usage: 763.8MB (peak: 3456.41MB), time: 69.48s.
[763.8MiB/69.48s] Finished Composer Cloud resolving.

**Comment by Toflar** [comment] 2019-10-31 15:27
> - Installation request for contao-components/dropzone (locked at 4.3.0) -> satisfiable by contao-components/dropzone[4.3.0].

Apparently you requested `contao-components/dropzone` in version 4.3 in your setup? Could you share your `composer.json` with us?

**Comment by AgenceUpMotion** [comment] 2019-10-31 15:32
{
    "type": "project",
    "require": {
        "asconsulting/member_autoactivate": "^1.0",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4",
        "contao/manager-bundle": "4.4.*",
        "contao/news-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4",
        "delahaye/dlh_googlemaps": "^2.4",
        "fipps/isotope-colorattribute-bundle": "^1.2",
        "isotope/isotope-core": "^2.6",
        "isotope/isotope_documents": "^1.0",
        "jedostyle/contao_isotope_attribute_listings": "^1.0",
        "onemarshall/contao-aos": "^1.0",
        "richardhj/contao-isotope_attribute_radio_image": "^1.0"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}

**Comment by Toflar** [comment] 2019-10-31 15:39
Ah I see.

`"contao/manager-bundle": "4.4."`

Autoregistration 2.* is not compatible with Contao 4.4, it only works as of 4.5.
Not sure if there's even a version that works for 4.4, @aschempp ?

**Comment by AgenceUpMotion** [comment] 2019-10-31 15:42
Yes it would be nice to have an intermediate version .., I only use the long support version (4.4)

**Comment by aschempp** [comment] 2019-11-01 14:27
duplicate of https://github.com/terminal42/contao-autoregistration/issues/5

**Closed as completed by aschempp** 2019-11-01 14:27 UTC

**Comment by AgenceUpMotion** [comment] 2019-11-12 13:38
Ou puis-je télécharger la version 1.3 ? sachant que la 2 n'est pas compatible ?

**Comment by richardhj** [comment] 2019-11-12 13:42
Edit the `composer.json` that is in the root folder of your website. Put the following line at the end of and within the `require` section:
`"terminal42/contao-autoregistration": "^1.3"`

Run an update with Contao Manager.

If you are not using Contao Manager, run `composer require terminal42/contao-autoregistration: ^1.3`

**Comment by richardhj** [comment] 2019-11-12 13:47
Sorry, my answer is invalid.

You can download the archive under https://github.com/terminal42/contao-autoregistration/releases/tag/1.3.0. Then you need to place the folder `autoregistration` under `system/modules`. Then clear the production cache in the Contao Manager and run the install tool.

Please note, that updating to Contao 4.8 is also a serious thing to consider.

**Comment by AgenceUpMotion** [comment] 2019-11-12 13:50
I will test, thx :) 
I only use versions of LTS contao.

So I wait patiently 4.9

**Comment by AgenceUpMotion** [comment] 2019-11-12 14:23
J'ai bien installé le module  et pu l'activer dans la structure du site mais il ne fonctionne pas. Lors de l'émission d'un formulaire de contact, j'ai une page d'erreur et en backoffice il n'est pas activé;

**Comment by richardhj** [comment] 2019-11-12 14:29
Pouvez-vous me parler de l'erreur ? Regardez « var/logs »

**Comment by AgenceUpMotion** [comment] 2019-11-12 14:40
[2019-11-12 14:20:27] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_url_fragment":"contao-manager/users.json","_route":"contao_catch_all"},"request_uri":"https://hetchmobilier.upmotion-prod.fr/contao-manager/users.json","method":"GET"} []
[2019-11-12 14:20:27] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2019-11-12 14:20:27] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: https://hetchmobilier.upmotion-prod.fr/contao-manager/users.json" at /var/www/clients/client5/web7/web/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: https://hetchmobilier.upmotion-prod.fr/contao-manager/users.json at /var/www/clients/client5/web7/web/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: https://hetchmobilier.upmotion-prod.fr/contao-manager/users.json at /var/www/clients/client5/web7/web/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:63)"} []

**Comment by richardhj** [comment] 2019-11-13 04:34
I don't think we can help here. Contao 4.9 is released in no fewer than three months. Pushing your project to Contao 4.8 now is the only thing I can recommend to you now.
